services:
  orientdb-node:
    image: orientdb:3.2.30
    container_name: orientdb-node
    environment:
      - ORIENTDB_ROOT_PASSWORD=admin
      - ORIENTDB_NODE_NAME=node_huy # Sửa thành tên node của mình (ví dụ: node_huy)
    ports:
      - "2424:2424"
      - "2480:2480"
    volumes:
      - ./hazelcast.xml:/orientdb/config/hazelcast.xml
      - ./default-distributed-db-config.json:/orientdb/config/default-distributed-db-config.json
    command: /orientdb/bin/server.sh -Ddistributed=true